#theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: pygments
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /Meetings/Minutes/:year/:month/:day/:title/
